# This file was generated by the {rix} R package v0.18.2 on 2026-09-23
# with following call:
# >rix(date = "2026-08-24",
#  > r_pkgs = c("brms",
#  > "palmerpenguins",
#  > "knitr",
#  > "rmarkdown"),
#  > system_pkgs = c("quarto",
#  > "cmdstan"),
#  > git_pkgs = list(package_name = "cmdstanr",
#  > repo_url = "https://github.com/stan-dev/cmdstanr",
#  > commit = "da99e2ba954658bdad63bffb738c4444c33a4e0e"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = paste("export CMDSTAN=$(dirname $(dirname $(command -v stan)))/opt/cmdstan",
#  > "export PRECOMPILED_HEADERS=false",
#  > sep = "\n"),
#  > r_ver = "4.6.1")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-08-24.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      brms
      knitr
      palmerpenguins
      rmarkdown;
  };
 
    cmdstanr = (pkgs.rPackages.buildRPackage {
      name = "cmdstanr";
      src = pkgs.fetchgit {
        url = "https://github.com/stan-dev/cmdstanr";
        rev = "da99e2ba954658bdad63bffb738c4444c33a4e0e";
        sha256 = "sha256-wXfOxBexnuL83fvCM+6qv6d7UhTLGq+Xhvja3lRfQpI=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          checkmate
          data_table
          jsonlite
          posterior
          processx
          R6
          withr
          rlang;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      cmdstan
      glibcLocales
      nix
      quarto
      R
      pandoc
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ cmdstanr rpkgs system_packages ];
    shellHook = ''
    export CMDSTAN=$(dirname $(dirname $(command -v stan)))/opt/cmdstan
export PRECOMPILED_HEADERS=false
  '';
  }; 
in
  {
    inherit pkgs shell;
  }
